import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Building2, ChevronDown, Plus, X } from 'lucide-react'
import { supabase } from './lib/supabase'
import type { Deal, DealStage, Lead, Property } from '../shared/types'

const stages: DealStage[] = ['New', 'Contacted', 'Interested', 'Site Visit', 'Negotiation', 'Booked', 'Closed', 'Lost']
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0)
async function api(path: string, init?: RequestInit) { const session = (await supabase?.auth.getSession())?.data.session; return fetch(path, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token}`, ...(init?.headers || {}) } }) }

export function DealsPage() {
  const [deals, setDeals] = useState<Deal[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState<Deal | null>(null)
  const load = async () => { setLoading(true); const response = await api('/api/deals'); const body = await response.json(); if (!response.ok) setError(body.error || 'Unable to load deals.'); else setDeals(body.data || []); setLoading(false) }
  useEffect(() => { load() }, [])
  const grouped = useMemo(() => Object.fromEntries(stages.map(stage => [stage, deals.filter(deal => deal.stage === stage)])) as Record<DealStage, Deal[]>, [deals])
  async function move(deal: Deal, stage: DealStage) { const response = await api(`/api/deals/${deal.id}`, { method: 'PATCH', body: JSON.stringify({ stage }) }); if (!response.ok) { const body = await response.json(); setError(body.error || 'Unable to move deal.'); return } await load() }
  return <section className="deals-page"><div className="heading"><div><p className="eyebrow">Workspace / Deals</p><h1>Deal pipeline</h1><p className="muted">Track every opportunity from first contact to close.</p></div><button className="primary" onClick={() => setFormOpen(true)}><Plus size={17}/> New deal</button></div>{error && <div className="error-box">{error}</div>}{loading ? <div className="empty">Loading deals…</div> : <div className="deal-board">{stages.map(stage => <div className="deal-column" key={stage}><div className="deal-column-head"><div><strong>{stage}</strong><span>{grouped[stage].length}</span></div><small>{money(grouped[stage].reduce((sum, deal) => sum + Number(deal.dealValue), 0))}</small></div>{grouped[stage].map(deal => <DealCard key={deal.id} deal={deal} onClick={() => setSelected(deal)} onMove={move}/>)}</div>)}</div>}{(formOpen || selected) && <DealModal deal={selected} onClose={() => { setFormOpen(false); setSelected(null) }} onSaved={() => { setFormOpen(false); setSelected(null); load() }}/>}</section>
}
function DealCard({ deal, onClick, onMove }: { deal: Deal; onClick: () => void; onMove: (deal: Deal, stage: DealStage) => void }) { return <article className="deal-card" onClick={onClick}><div className="deal-card-top"><span className="status-pill">{deal.stage}</span><ChevronDown size={15}/></div><h2>{deal.lead?.name || 'Lead'}</h2><p>{deal.property?.title || 'Property'}</p><strong>{money(Number(deal.dealValue))}</strong><div className="deal-card-foot"><span>{deal.agent?.name || 'Assigned agent'}</span><select aria-label={`Move ${deal.lead?.name || 'deal'}`} value={deal.stage} onClick={e => e.stopPropagation()} onChange={e => onMove(deal, e.target.value as DealStage)}>{stages.map(stage => <option key={stage}>{stage}</option>)}</select></div></article> }
function DealModal({ deal, onClose, onSaved }: { deal: Deal | null; onClose: () => void; onSaved: () => void }) { const [leads, setLeads] = useState<Lead[]>([]); const [properties, setProperties] = useState<Property[]>([]); const [leadId, setLeadId] = useState(deal?.leadId || ''); const [propertyId, setPropertyId] = useState(deal?.propertyId || ''); const [value, setValue] = useState(String(deal?.dealValue || '')); const [rate, setRate] = useState('2'); const [stage, setStage] = useState<DealStage>(deal?.stage || 'New'); const [error, setError] = useState(''); useEffect(() => { Promise.all([api('/api/leads'), api('/api/properties?pageSize=50')]).then(async ([l, p]) => { const lb = await l.json(); const pb = await p.json(); setLeads(lb.data || []); setProperties(pb.data || []) }) }, [])
  async function submit(event: React.FormEvent) { event.preventDefault(); const response = await api(deal ? `/api/deals/${deal.id}` : '/api/deals', { method: deal ? 'PATCH' : 'POST', body: JSON.stringify({ leadId, propertyId, dealValue: Number(value), commissionRate: Number(rate), stage }) }); const body = await response.json(); if (!response.ok) return setError(body.error || 'Unable to save deal.'); onSaved() }
  return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-title"><div><p className="eyebrow">{deal ? 'Edit deal' : 'Create deal'}</p><h2>{deal ? deal.lead?.name : 'New opportunity'}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></div><label>Lead<select required value={leadId} onChange={e => setLeadId(e.target.value)} disabled={Boolean(deal)}><option value="">Select lead</option>{leads.map(lead => <option value={lead.id} key={lead.id}>{lead.name}</option>)}</select></label><label>Property<select required value={propertyId} onChange={e => setPropertyId(e.target.value)} disabled={Boolean(deal)}><option value="">Select property</option>{properties.map(property => <option value={property.id} key={property.id}>{property.title}</option>)}</select></label><div className="form-split"><label>Deal value<input required type="number" min="1" value={value} onChange={e => setValue(e.target.value)}/></label><label>Commission %<input type="number" min="0" step="0.1" value={rate} onChange={e => setRate(e.target.value)}/></label></div><label>Stage<select value={stage} onChange={e => setStage(e.target.value as DealStage)}>{stages.map(item => <option key={item}>{item}</option>)}</select></label>{error && <p className="error">{error}</p>}<button className="primary" type="submit">{deal ? 'Save changes' : 'Create deal'}</button></form></div> }
export function DealsShell({ onLogout }: { onLogout: () => void }) { return <div className="shell"><header className="topbar"><div className="brand"><Building2 size={20}/> Dealflow</div><nav className="activity-nav"><a href="/">Properties</a><a href="/deals">Deals</a><a href="/site-visits">Site visits</a><a href="/follow-ups">Follow-ups</a></nav><button className="secondary" onClick={onLogout}>Sign out</button></header><main className="page"><DealsPage/></main></div> }
