import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, Clock3, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { supabase } from './lib/supabase'
import type { FollowUp, SiteVisit } from '../shared/types'

async function api(path: string, options: RequestInit = {}) { const session = (await supabase?.auth.getSession())?.data.session; const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token}`, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Request failed'); return body.data }
const localDate = (value: string) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })

export function VisitsPage({ kind = 'visits' }: { kind?: 'visits' | 'followups' }) { const [visits,setVisits]=useState<SiteVisit[]>([]); const [followUps,setFollowUps]=useState<FollowUp[]>([]); const [tab,setTab]=useState(kind); const [error,setError]=useState(''); const [formOpen,setFormOpen]=useState(false); const [refresh,setRefresh]=useState(0)
  useEffect(()=>{ Promise.all([api('/api/site-visits'),api('/api/follow-ups')]).then(([v,f])=>{setVisits(v||[]);setFollowUps(f||[])}).catch(e=>setError(e.message)) },[refresh])
  const today = new Date(); const day = (value:string) => new Date(value).toDateString() === today.toDateString(); const overdue = followUps.filter(x=>x.status==='Pending' && new Date(x.dueAt)<today); const todays = followUps.filter(x=>x.status==='Pending' && day(x.dueAt)); const upcoming = followUps.filter(x=>x.status==='Pending' && new Date(x.dueAt)>=today && !day(x.dueAt)); const todaysVisits=visits.filter(x=>day(x.scheduledAt))
  async function update(path:string, payload:object){try{await api(path,{method:'PUT',body:JSON.stringify(payload)});setRefresh(x=>x+1)}catch(e){setError((e as Error).message)}}
  return <div className="workspace"><div className="heading"><div><p className="eyebrow">Workspace / Activity</p><h1>{tab==='visits'?'Site visits':'Follow-ups'}</h1><p className="muted">Keep every conversation and appointment moving forward.</p></div><button className="primary" onClick={()=>setFormOpen(true)}><Plus size={17}/> Add {tab==='visits'?'site visit':'follow-up'}</button></div><div className="activity-widgets"><Widget label="Overdue follow-ups" value={overdue.length} tone="danger"/><Widget label="Today's follow-ups" value={todays.length}/><Widget label="Upcoming follow-ups" value={upcoming.length}/><Widget label="Today's site visits" value={todaysVisits.length}/></div><div className="activity-tabs"><button className={tab==='visits'?'active':''} onClick={()=>setTab('visits')}><CalendarDays size={16}/> Site visits</button><button className={tab==='followups'?'active':''} onClick={()=>setTab('followups')}><Clock3 size={16}/> Follow-ups</button></div>{error&&<div className="error-box">{error}</div>}{tab==='visits'?<div className="activity-list">{visits.map(v=><article className="activity-card" key={v.id}><div><span className={`status-pill ${v.status.toLowerCase().replace(' ','-')}`}>{v.status}</span><h2>{v.lead?.name||v.leadId}</h2><p className="muted">{v.property?.title||v.propertyId} · {localDate(v.scheduledAt)}</p>{v.feedback&&<p className="body-copy">{v.feedback}</p>}</div><div className="activity-actions"><select value={v.status} onChange={e=>update(`/api/site-visits/${v.id}`,{status:e.target.value})}><option>Scheduled</option><option>Completed</option><option>Cancelled</option><option>Rescheduled</option><option>No Show</option></select>{v.status==='Completed'&&<button className="secondary" onClick={()=>{const feedback=prompt('Add feedback',v.feedback||''); if(feedback!==null)update(`/api/site-visits/${v.id}`,{feedback})}}><Check size={15}/> Feedback</button>}</div></article>)}{!visits.length&&<Empty label="No site visits yet."/>}</div>:<div className="activity-list">{followUps.map(f=><article className="activity-card" key={f.id}><div><span className={`status-pill ${f.priority.toLowerCase()}`}>{f.priority} priority</span><h2>{f.lead?.name||f.leadId}</h2><p className="body-copy">{f.note}</p><p className="muted">Due {localDate(f.dueAt)}</p></div><div className="activity-actions"><button className="secondary" onClick={()=>update(`/api/follow-ups/${f.id}`,{status:f.status==='Completed'?'Pending':'Completed'})}><Check size={15}/> {f.status==='Completed'?'Reopen':'Complete'}</button></div></article>)}{!followUps.length&&<Empty label="No follow-ups yet."/>}</div>}{formOpen&&<ActivityForm kind={tab} onClose={()=>setFormOpen(false)} onSaved={()=>{setFormOpen(false);setRefresh(x=>x+1)}}/>}</div> }
function Widget({label,value,tone}:{label:string;value:number;tone?:string}){return <div className={`activity-widget ${tone||''}`}><span>{label}</span><strong>{value}</strong></div>}
function Empty({label}:{label:string}){return <div className="empty"><RefreshCw size={25}/><h2>{label}</h2><p>Add an activity to start tracking your pipeline.</p></div>}
function ActivityForm({kind,onClose,onSaved}:{kind:'visits'|'followups';onClose:()=>void;onSaved:()=>void}){const [lead,setLead]=useState('');const [property,setProperty]=useState('');const [date,setDate]=useState('');const [note,setNote]=useState('');const [error,setError]=useState(''); async function submit(e:React.FormEvent){e.preventDefault();try{await api(kind==='visits'?'/api/site-visits':'/api/follow-ups',{method:'POST',body:JSON.stringify(kind==='visits'?{lead,property,scheduledAt:new Date(date).toISOString(),status:'Scheduled',feedback:note}:{lead,dueAt:new Date(date).toISOString(),priority:'Medium',status:'Pending',note})});onSaved()}catch(e){setError((e as Error).message)}}return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="form-top"><div><p className="eyebrow">New activity</p><h2>{kind==='visits'?'Schedule site visit':'Create follow-up'}</h2></div><button type="button" className="secondary" onClick={onClose}>Close</button></div><label>Lead ID<input value={lead} onChange={e=>setLead(e.target.value)} required placeholder="Lead UUID"/></label>{kind==='visits'&&<label>Property ID<input value={property} onChange={e=>setProperty(e.target.value)} required placeholder="Property UUID"/></label>}<label>{kind==='visits'?'Scheduled time':'Due time'}<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>{kind==='visits'?'Feedback':'Note'}<textarea value={note} onChange={e=>setNote(e.target.value)} required /></label>{error&&<p className="error">{error}</p>}<button className="primary" type="submit">Save activity</button></form></div>}
export function DashboardActivityWidgets(){return null}
