import { relations } from 'drizzle-orm'
import { boolean, integer, pgEnum, pgTable, numeric, text, timestamp, uuid, index, uniqueIndex } from 'drizzle-orm/pg-core'

const timestamps = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }

export const userRoleEnum = pgEnum('user_role', ['admin', 'broker', 'agent'])
export const propertyTypeEnum = pgEnum('property_type', ['Apartment', 'Villa', 'Plot', 'House', 'Commercial', 'Office', 'Shop', 'Other'])
export const listingTypeEnum = pgEnum('listing_type', ['Sale', 'Rent'])
export const propertyStatusEnum = pgEnum('property_status', ['Available', 'Under Negotiation', 'Booked', 'Sold', 'Rented', 'Inactive'])
export const leadSourceEnum = pgEnum('lead_source', ['99acres', 'MagicBricks', 'Housing.com', 'Website', 'Referral', 'Manual', 'Other'])
export const leadStatusEnum = pgEnum('lead_status', ['New', 'Contacted', 'Interested', 'Site Visit', 'Negotiation', 'Booked', 'Closed', 'Lost'])
export const visitStatusEnum = pgEnum('visit_status', ['Scheduled', 'Completed', 'Cancelled', 'Rescheduled', 'No Show'])
export const followUpPriorityEnum = pgEnum('follow_up_priority', ['Low', 'Medium', 'High'])
export const followUpStatusEnum = pgEnum('follow_up_status', ['Pending', 'Completed', 'Cancelled'])
export const dealStatusEnum = pgEnum('deal_status', ['Open', 'Closed', 'Cancelled'])

export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), email: text('email').notNull(), role: userRoleEnum('role').notNull().default('agent'), ...timestamps }, table => [uniqueIndex('users_email_idx').on(table.email)])
export const properties = pgTable('properties', { id: uuid('id').defaultRandom().primaryKey(), title: text('title').notNull(), propertyType: propertyTypeEnum('property_type').notNull(), listingType: listingTypeEnum('listing_type').notNull(), location: text('location').notNull(), city: text('city').notNull(), area: integer('area').notNull(), bedrooms: integer('bedrooms'), bathrooms: integer('bathrooms'), floor: integer('floor'), totalFloors: integer('total_floors'), price: numeric('price', { precision: 14, scale: 2 }).notNull(), description: text('description'), amenities: text('amenities').array().notNull().default([]), status: propertyStatusEnum('status').notNull().default('Available'), ownerName: text('owner_name'), ownerPhone: text('owner_phone'), agentId: uuid('agent_id').references(() => users.id, { onDelete: 'set null' }), lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }), ...timestamps }, table => [index('properties_city_idx').on(table.city), index('properties_agent_idx').on(table.agentId), index('properties_status_idx').on(table.status)])
export const leads = pgTable('leads', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), phone: text('phone').notNull(), email: text('email'), budgetMin: numeric('budget_min', { precision: 14, scale: 2 }), budgetMax: numeric('budget_max', { precision: 14, scale: 2 }), preferredLocation: text('preferred_location'), propertyType: propertyTypeEnum('property_type'), bedrooms: integer('bedrooms'), minArea: integer('min_area'), purpose: listingTypeEnum('purpose'), source: leadSourceEnum('source').notNull().default('Manual'), sourceLeadId: text('source_lead_id'), status: leadStatusEnum('status').notNull().default('New'), assignedAgentId: uuid('assigned_agent_id').references(() => users.id, { onDelete: 'set null' }), notes: text('notes'), ...timestamps }, table => [index('leads_status_idx').on(table.status), index('leads_agent_idx').on(table.assignedAgentId), uniqueIndex('leads_source_id_idx').on(table.source, table.sourceLeadId)])
export const siteVisits = pgTable('site_visits', { id: uuid('id').defaultRandom().primaryKey(), leadId: uuid('lead_id').notNull().references(() => leads.id, { onDelete: 'cascade' }), propertyId: uuid('property_id').notNull().references(() => properties.id, { onDelete: 'cascade' }), agentId: uuid('agent_id').references(() => users.id, { onDelete: 'set null' }), scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull(), status: visitStatusEnum('status').notNull().default('Scheduled'), feedback: text('feedback'), ...timestamps }, table => [index('site_visits_scheduled_idx').on(table.scheduledAt), index('site_visits_lead_idx').on(table.leadId)])
export const followUps = pgTable('follow_ups', { id: uuid('id').defaultRandom().primaryKey(), leadId: uuid('lead_id').notNull().references(() => leads.id, { onDelete: 'cascade' }), agentId: uuid('agent_id').references(() => users.id, { onDelete: 'set null' }), dueAt: timestamp('due_at', { withTimezone: true }).notNull(), note: text('note').notNull(), priority: followUpPriorityEnum('priority').notNull().default('Medium'), status: followUpStatusEnum('status').notNull().default('Pending'), ...timestamps }, table => [index('follow_ups_due_idx').on(table.dueAt), index('follow_ups_agent_idx').on(table.agentId)])
export const deals = pgTable('deals', { id: uuid('id').defaultRandom().primaryKey(), leadId: uuid('lead_id').notNull().references(() => leads.id, { onDelete: 'restrict' }), propertyId: uuid('property_id').notNull().references(() => properties.id, { onDelete: 'restrict' }), agentId: uuid('agent_id').references(() => users.id, { onDelete: 'set null' }), dealValue: numeric('deal_value', { precision: 14, scale: 2 }).notNull(), commission: numeric('commission', { precision: 14, scale: 2 }).notNull(), status: dealStatusEnum('status').notNull().default('Open'), closedAt: timestamp('closed_at', { withTimezone: true }), ...timestamps }, table => [index('deals_agent_idx').on(table.agentId), index('deals_status_idx').on(table.status), uniqueIndex('deals_lead_property_idx').on(table.leadId, table.propertyId)])

export const userRelations = relations(users, ({ many }) => ({ properties: many(properties), leads: many(leads), siteVisits: many(siteVisits), followUps: many(followUps), deals: many(deals) }))
export const propertyRelations = relations(properties, ({ one, many }) => ({ agent: one(users, { fields: [properties.agentId], references: [users.id] }), siteVisits: many(siteVisits), deals: many(deals) }))
export const leadRelations = relations(leads, ({ one, many }) => ({ agent: one(users, { fields: [leads.assignedAgentId], references: [users.id] }), siteVisits: many(siteVisits), followUps: many(followUps), deals: many(deals) }))
export const siteVisitRelations = relations(siteVisits, ({ one }) => ({ lead: one(leads, { fields: [siteVisits.leadId], references: [leads.id] }), property: one(properties, { fields: [siteVisits.propertyId], references: [properties.id] }), agent: one(users, { fields: [siteVisits.agentId], references: [users.id] }) }))
export const followUpRelations = relations(followUps, ({ one }) => ({ lead: one(leads, { fields: [followUps.leadId], references: [leads.id] }), agent: one(users, { fields: [followUps.agentId], references: [users.id] }) }))
export const dealRelations = relations(deals, ({ one }) => ({ lead: one(leads, { fields: [deals.leadId], references: [leads.id] }), property: one(properties, { fields: [deals.propertyId], references: [properties.id] }), agent: one(users, { fields: [deals.agentId], references: [users.id] }) }))

export type User = typeof users.$inferSelect
export type Property = typeof properties.$inferSelect
export type Lead = typeof leads.$inferSelect
export type SiteVisit = typeof siteVisits.$inferSelect
export type FollowUp = typeof followUps.$inferSelect
export type Deal = typeof deals.$inferSelect
